[build]
  base = "./"
  publish = "./dist/"
  command = "npm install --legacy-peer-deps && npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
