[build]
  base = "./"
  publish = "./dist/"
  command = "nvm use 18.20.4 && npm install --legacy-peer-deps && npm run build"
  
[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[template.environment]
  NAME = "enter Name of the receiver"
  PIC = "enter web url of the receiver's image"
  SCROLL_MSG = "enter web url of scroll message (telegra.ph article)"
  HBD_MSG = "enter custom birthday message (optional)"
